Разметка
htmlacademy-htmlcss/2157055-device-35 pull request #2
Opened 2022-10-05 13:33 UTC by Yagaweb

Создание разметки главной страницы сайта и старицы "каталог"

2022-10-06 09:07 UTC, Dima-Dim requested changes

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +            <a class="navigation-link" href="#">
Это не ссылка, это форма поиска. И она не относится к основной навигации по сайту.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +              <span class="button">
А это интерактивный элемент.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +        <ul class="page-navigation-list">
А вот этот список похож на основную навигацию.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +          <b>подробнее</b>
Сейчас мы занимаемся только разметкой, а тег `b` больше про стилизацию. Не нужно пока его использовать. Тоже самое касается и других тегов `b` в разметке.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +      <section class="popular-products">
Здесь нужно выделить слайды, в отдельные контейнера. Решить что является частью слайда и будет в каждом из таких контейнеров, а что нет и будет отдельно от них.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +            <img class="product-categories-sign" alt="Очки виртуальной реальности" src="">
Это декоративное изображение и его не должно быть в разметке.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +            <p>Виртуальная реальность</p>
Если не будет тега `img`, то может и без тега `p` получится обойтись.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +            <p class="extra-info-discription">
Нет, табы с названиями отдельно, содержимое табов отдельно. Почти как слайдер.

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +          <il class="delivery-ways-item">
Перед отправкой на проверку необходимо проверить получившийся html валидатором validator.w3.org/nu

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +          <p class="e-mail_for_subscription">
https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-06

2022-10-06 09:07 UTC, Dima-Dim commented on index.html
> +          <p class="footer-address-text">Санкт-Петербург, набережная реки Карповки, 5, литера П.</p>
Тоже лишний тег `p`.

2022-10-07 22:03 UTC, Yagaweb commented on index.html
> +            <a class="navigation-link" href="#">
Я правильно понимаю, что мне нужно вынести форму поиска за придел навигации? Она будет находится в шапке сайта обособлено.

2022-10-07 22:11 UTC, Yagaweb commented on index.html
> +      <section class="popular-products">
Прошу прощения, не до конца понял. Подразумевается, что мне надо обьединить картинку с кнопками для перемотки в контейнере или в этот контейнер поместить также описание?

2022-10-07 22:14 UTC, Yagaweb commented on index.html
> +            <p>Виртуальная реальность</p>
Там не получится без тега <img>, так как там присутствует декоративная картинка и текст. Я не вижу другой способ оформления данного списка

2022-10-08 13:21 UTC, Dima-Dim commented on index.html
> +            <a class="navigation-link" href="#">
Да. поиск не является частью навигации.

2022-10-08 13:23 UTC, Dima-Dim commented on index.html
> +            <p>Виртуальная реальность</p>
Получится, а как именно вам раскажут в разделе про декоратитивные Декоративные элементы.

2022-10-08 13:25 UTC, Dima-Dim commented on index.html
> +      <section class="popular-products">
Тебе нужно составить логическую структуру, разобрав макет на составные части и я тебе предлагают подумать над тем, что входит в состав одного слайда, в первую очередь. Не что куда перенести, а что чем является. После станет понятно что куда перенести, а точнее как правильно всё это разместить в разметке.

2022-10-10 09:58 UTC, Dima-Dim requested changes

2022-10-10 09:58 UTC, Dima-Dim commented on index.html
> +            <span class="visually-hidden">Предыдущий товар</span>
Судя по тексту это кнопки управления слайдером и если это так, то они не являются часть слайда.

2022-10-10 09:58 UTC, Dima-Dim commented on index.html
> +            <h3 class="extra-info-title"><button>Доставка</button></h3>
Тег h3 тут лишний, потому что кроме "заголовков" тут ничего нет.

2022-10-10 09:58 UTC, Dima-Dim commented on index.html
> +            <h3 class="extra-description-title">Доставка</h3>
А вот тут заголовки действительно заголовки какого-то текста.

2022-10-10 09:58 UTC, Dima-Dim commented on index.html
> +      <a class="delivery" href="#"><b>Доставим редкий товар под заказ</b></a>
Тег `b` это про стилизацию, а у нас пока только разметка.

2022-10-10 09:58 UTC, Dima-Dim commented on index.html
> +            <p class="delivery-ways-example">
Можно обойтись без тега `p` и разместить текст сразу в теге `li`.

2022-10-10 12:51 UTC, Yagaweb commented on index.html
> +            <h3 class="extra-description-title">Доставка</h3>
Я тут оставляю как есть, верно?

2022-10-11 03:28 UTC, Dima-Dim commented on index.html
> +            <h3 class="extra-description-title">Доставка</h3>
Да.

2022-10-12 03:50 UTC, merged