Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2157055-device-35 pull request #5
Opened 2022-11-01 13:14 UTC by Yagaweb

---
:mortar_board: [Сетка страниц и крупных блоков на флексах](https://up.htmlacademy.ru/htmlcss/35/user/2157055/tasks/10)

:boom: https://htmlacademy-htmlcss.github.io/2157055-device-35/5/

2022-11-02 07:17 UTC, Dima-Dim requested changes
Убрать лишние элементы. Расставить отступы для вложенных тегов.

2022-11-02 07:17 UTC, Dima-Dim commented on catalog.html
> +      <div class="logo-container">
Почему не один центровщик на весь `header`?

2022-11-02 07:17 UTC, Dima-Dim commented on catalog.html
> +        <ul class="header-categories-list visually-hidden" hidden>
Класса `visually-hidden` не хватило?

2022-11-02 07:17 UTC, Dima-Dim commented on catalog.html
> +          <h2 class="filter-title">Фильтр:</h2>
Если появляется вложенность, то нужно учитывать это и в отступах.

2022-11-02 07:17 UTC, Dima-Dim commented on index.html
> +            <div class="product-image">
Для чего этот контейнер?

2022-11-02 07:17 UTC, Dima-Dim commented on index.html
> +                <b>подробнее</b>
К чему столько лишних тегов? https://up.htmlacademy.ru/htmlcss/35/criteries#HTML-06

2022-11-02 07:17 UTC, Dima-Dim commented on styles/styles.css
> +  padding-left: 37.5px;
Где-то в примерах или материалах есть точность больше целых?

2022-11-02 10:14 UTC, Yagaweb commented on catalog.html
> +        <ul class="header-categories-list visually-hidden" hidden>
Я скрыл для удобства. Просто в 5 разделе сказали пока не прописывать класс "visually-hidden". Мне убрать атрибут или можно пока оставить, до описание класса?

2022-11-02 10:23 UTC, Yagaweb commented on index.html
> +                <b>подробнее</b>
Это только тега `<b>` касается?

2022-11-03 06:39 UTC, Dima-Dim commented on catalog.html
> +        <ul class="header-categories-list visually-hidden" hidden>
Потом не забудь убрать :)

2022-11-03 06:40 UTC, Dima-Dim commented on index.html
> +                <b>подробнее</b>
В данном месте да. Но вообще в целом есть подобное и в других местах. Придерживайся критерия.

2022-11-04 13:21 UTC, Dima-Dim requested changes
Не забывай про validator.w3.org/nu/ иначе сложно понять всё ли корректно с вложенностью.

2022-11-06 09:16 UTC, merged